Polished formatting / Reorganized some stuff
octobanzo/octobanzo pull request #13
Opened 2020-08-30 17:55 UTC by zalusan

2020-09-05 21:08 UTC, hadenpf requested changes
Thank you for the PR and contributing! Overall love the ideas and some of the changes you made here, but some of it seems a little dramatic & goes against the original idea for the layout and formatting. I'll accept the PR if you don't mind making some of the changes I requested, otherwise when I get around to it I'll pop in and shuffle the things around.

Thanks again for the contribution :heart:

2020-09-05 21:08 UTC, hadenpf commented on README.md
> +Moderate quickly and easily — you don't even have to do anything while the spam is happening.
I like the way you redid this line!

2020-09-05 21:08 UTC, hadenpf commented on README.md
> +## Before You Commit:
Not sure if I agree with the move of this section — it's currently in a prominent position to emphasize the incompleteness and current instability of the project.

2020-09-05 21:08 UTC, hadenpf commented on README.md
> +**The super powerful [Discord](https://discord.com) bot, powered by machine learning.**
Could re-add the "Currently WIP" text here. I want to emphasize that the bot is not ready for production.

2020-09-05 21:08 UTC, hadenpf commented on README.md
> +## Commands
One of the hallmark features I want to make obvious with Octobanzo is the *lack* of certain commands — e.g. kick, ban. Having a "Commands > Moderation" section that highlights a feature that explicitly lacks commands sort of goes against that.

2020-09-05 21:08 UTC, hadenpf commented on README.md
> +## Usage
Might want to comment this out, since it's adding a header for a section that doesn't seem to exist yet.

2020-09-05 21:08 UTC, hadenpf commented on README.md
> -## Moderation Heaven
Part of the way I wrote the README is to highlight the major features, rather than having a boring list-format sort of thing [e.g. "Commands", "Features", etc. Show, don't tell.]. Hence "Moderation Heaven", "Language Processing", "Open-Source and Transparent"

2020-09-05 21:21 UTC, hadenpf commented on README.md
> +## Before You Commit:
Added a notice on line 1-3 that leads to this section.

2020-09-05 21:24 UTC, hadenpf commented
I made some changes because I want to get this merged in fairly soon — please feel free to suggest/make any other changes you'd like to see before I do a full merge-in!

2020-09-05 22:49 UTC, zalusan commented
shut the fuck up 😐🖕

2020-09-05 23:00 UTC, hadenpf commented
> I will get to it ASAP, sorry for the troubles. 👍

No need to apologize! I appreciate all contributions, especially giving attention to README. Please feel free to suggest any other changes you see fit :)

2020-09-07 09:29 UTC, hadenpf approved these changes

2020-09-07 09:29 UTC, merged